#!/usr/bin/env php
<?php

require_once('consolator.phar');

$application = \AlexanderC\Consolator\bootstrap([
    'commandPaths' => __DIR__,
    'autoload' => ["AlexanderC\\Consolator\\Test\\" => __DIR__]
]);

$application->terminate($application->run());